version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: redis

  app:
    build: .
    container_name: nest-app
    depends_on:
      - postgres
      - redis
    environment:
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      REDIS_URL: ${REDIS_URL}
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: sh -c "npm run migration:run && npm run start:dev"

volumes:
  pgdata:
